### PR TITLE
Do not append '\n' at the end of the data.

### PR DESCRIPTION
**Pull request by pr3mar**
Should the user need '\n' let him/her add it manually, please approve this PR it has been a terrible pain for quite some time.

### CODE REVIEW

**Comment by pr3mar** [comment]
ping @MacInnis

**Comment by pr3mar** [comment]
ping @MacInnis

**Comment by pr3mar** [comment]
ping @MacInnis

**Comment by MacInnis** [comment]
I cannot approve this PR in its current form.  KDG's behavior of adding a \n character to the end of each record has been in place since the inception of the tool.  Simply removing that functionality will be a breaking change to the many users who now expect the newline character to be added to the end of each record.  The reason the newline character is added is because it is a best practice for data producers to do so, particularly if the data is being sent to Firehose with a destination of S3.  See [here](https://docs.aws.amazon.com/firehose/latest/APIReference/API_PutRecord.html).  

The only way I will approve is if you make it optional for users, where the default behavior is to add the newline character.  If you make it a choice by adding a checkbox with text similar to "Delimit records with a newline character" (Yes/No), and Yes is the default setting, I will approve.

**Pull request closed without merging**
